[package]
name = "erc1155"
version = "0.1.0"

[lib]
name = "erc1155"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
rules_account = { git = "https://github.com/ruleslabs/starknet-rules-account.git" }
starknet = ">=1.0.0"

[[target.starknet-contract]]
